# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'couple-housework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for couple-housework
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

  target 'couple-houseworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'couple-houseworkUITests' do
    # Pods for testing
  end

end
